name: markdown_quill
description: Provides converters to convert from markdown to quill (Delta)
  format and vice versa.
version: 2.0.0
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.18.0
  flutter_quill: ^9.3.1
  markdown: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  very_good_analysis: ^5.0.0
